"""add multi currency base 2024-02-19

Revision ID: d4f662e0badd
Revises: 657df5575c89
Create Date: 2024-02-19 16:22:10.172260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f662e0badd'
down_revision = '657df5575c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('original_amount', sa.Numeric(), nullable=False))
    op.add_column('expenses', sa.Column('original_currency', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_expenses_original_amount'), 'expenses', ['original_amount'], unique=False)
    op.create_index(op.f('ix_expenses_original_currency'), 'expenses', ['original_currency'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_original_currency'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_original_amount'), table_name='expenses')
    op.drop_column('expenses', 'original_currency')
    op.drop_column('expenses', 'original_amount')
    # ### end Alembic commands ###
